/*
     -----------------------------------------------------------

     Code generated by CRA.ModelLayer.ACC - API Code Generator
     http://components.biomamodelling.org/components/acc/help/ 

     Loic Manceau
     loic.manceau@inra.fr
     INRA
     5/27/2019 1:15:21 PM

     -----------------------------------------------------------
*/

using System;
using CRA.AgroManagement;
using CRA.ModelLayer.Strategy;


namespace SiriusQualityMaizeLAI
{
    /// <summary>
    /// SiriusQualityMaizeLAI component model interface   
    /// </summary>
    public interface IStrategySiriusQualityMaizeLAI : IStrategy
    {
        /// <summary>
        /// Calculate method for models
        /// </summary>
        /// <param name=m>MaizeLAIState Domain class contains the accessors to values</param>
        /// <param name=m1>MaizeLeafState Domain class contains the accessors to values</param>
        /// <param name=m2>MaizeLeafState Domain class contains the accessors to values</param>
        /// <param name=ae>AgroManagement objects of impact parameters</param>
        void Estimate
        ( MaizeLAIState m, MaizeLeafState m1, MaizeLeafState m2, ActEvents ae);
        
        /// <summary>
        /// Test of pre conditions
        /// </summary>
        /// <param name=m>MaizeLAIState Domain class contains the accessors to values</param>
        /// <param name=m1>MaizeLeafState Domain class contains the accessors to values</param>
        /// <param name=m2>MaizeLeafState Domain class contains the accessors to values</param>
        /// <param name=callID>Preconditions test context</param>
        /// <returns>List of violations</returns>
        string TestPreConditions( MaizeLAIState m, MaizeLeafState m1, MaizeLeafState m2, string callID);
        
        /// <summary>
        /// Test of post-conditions
        /// </summary>
        /// <param name=m>MaizeLAIState Domain class contains the accessors to values</param>
        /// <param name=m1>MaizeLeafState Domain class contains the accessors to values</param>
        /// <param name=m2>MaizeLeafState Domain class contains the accessors to values</param>
        /// <param name=callID>Postconditions test context</param>
        /// <returns>List of violations</returns>
        string TestPostConditions( MaizeLAIState m, MaizeLeafState m1, MaizeLeafState m2, string callID);
    
        /// <summary>
        /// Set parameters to the default value
        /// </summary>
        void SetParametersDefaultValue();
    }
}
